spring:
  application:
    name : demo4
  main:
    banner-mode : off
  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: artiom
    password: admin
    generate-unique-name: false
    name: tacocloud
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    org.thymeleaf: DEBUG

server:
  port: 8080
  ssl:
    key-store: classpath:/config/keystore.p12
    key-store-password: 123456
    key-password: 123456
    key-store-type: PKCS12
    key-alias: tacocloud
management:
  endpoints:
    web:
      exposure:
        include: health